#!/bin/bash -e

source $OPENSHIFT_CARTRIDGE_SDK_BASH

echo "Creating sample data"

${OPENSHIFT_ORACLE_CLIENT_INST_DIR}sqlplus "${OPENSHIFT_ORACLE_DB_USERNAME}/${OPENSHIFT_ORACLE_DB_PASSWORD}@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=${OPENSHIFT_ORACLE_DB_HOST})(PORT=${OPENSHIFT_ORACLE_DB_PORT}))(CONNECT_DATA=(SERVICE_NAME=${OPENSHIFT_ORACLE_DB_NAME})))" @${OPENSHIFT_REPO_DIR}scripts/create_table.sql

if [ $? == 0 ] ; then 
	echo "Sample data successfully created"
   else 
	echo "Error in creating sample data"
   esle
fi
